apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 0
  selector:
    matchLabels:
      app: flask1
  template:
    metadata:
      labels:
        app: flask1
    spec:
      containers:
      - name: flask1
        image: 172.17.0.1:5000/startupv2:1
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
             path: /startupv2
             port: 5000

